Chf 53/rating component
VicenteEspinosa/frontendChefsitos pull request #24
Opened 2022-06-18 19:01 UTC by cahinostroza

## Descripción General
Se crea el componente de rating

## Detalles

* Se agregan las funciones `rate` y `deleteRate` a `RecipeService`

* Se crea el componente `Like`

* Se actualiza el componente `Recipes` para que llame a `Like`

* Se actualiza `RecipePage` para que llame a `Like`

* Se crean test para `RecipePage` y `Like`

## Probar cambios

Entrar a `http://localhost:3000/recipes` o la página de una receta y probar el componente para dar like o dislike

## Tarjetas en Jira
[CHF-53](https://tfflores.atlassian.net/browse/CHF-53)

2022-06-19 02:31 UTC, VicenteEspinosa approved these changes
Todo bien pero creo que quedaría mejor si el like es de otro color, como #445c8f por ejemplo

2022-06-19 02:34 UTC, tfflores requested changes
Todo bien!! Eso sí, apoyo la sugerencia de @VicenteEspinosa, con ese cambio de color quedaría mejor visualmente.

2022-06-21 18:16 UTC, cahinostroza commented
@tfflores @VicenteEspinosa  no estoy tan deacuerdo, pq estariamos mezclando muchas tonalidades, con el navbar de un color, las tarjetas de las recetas de otro y los likes de otros, pero la vdd es que me da lo mismo a estas alturas del semestre jaja, así que ahí hice el cambio.

2022-06-21 18:22 UTC, tfflores approved these changes

2022-06-21 18:22 UTC, merged